#!/bin/bash
set -euo pipefail

# labextensions
jupyter labextension install @jupyter-widgets/jupyterlab-manager@1.1.0 \
                             @jupyterlab/geojson-extension \
                             @pyviz/jupyterlab_pyviz \
                             jupyter-matplotlib@0.5.0 \
                             jupyter-leaflet \
                             dask-labextension
