#!/bin/bash
set -euo pipefail

# labextensions
jupyter labextension install @jupyter-widgets/jupyterlab-manager \
                             @jupyterlab/geojson-extension \
                             @pyviz/jupyterlab_pyviz \
                             jupyter-matplotlib \
                             jupyter-leaflet \
                             dask-labextension

#install from conda-forge?
pip install nbresuse
jupyter serverextension enable --py nbresuse --sys-prefix
jupyter nbextension install --py nbresuse --sys-prefix
jupyter nbextension enable --py nbresuse --sys-prefix

mandb
